### ISSUE TITLE
The listening port for the web application should be configurable.

### ISSUE THREAD

**Issue by grogsaxle** [blackhillsinfosec/RITA#2]
With my current installation I have another process already running on port 5000.  Would be great to have the application read a configuration file or take a command line option for what port to listen on, while keeping the 5000 port as the default.

**Comment by blackhillsinfosec** [comment]
Hey, thanks for the line. We've added some minimal argument parsing to include changing the listening port, turning off/on debugging, and turning off/on threading. There's also now a minimal help.
